// <auto-generated />
namespace NinjaDomain.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_Ninja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_Ninja));
        
        string IMigrationMetadata.Id
        {
            get { return "201608310039323_new_Ninja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
